[package]
name = "minif2f"
version = "1.0"
lean_version = "leanprover-community/lean:3.33.0"
path = "lean/src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "4a02fd3bf80d43fd7965c1bfc3361765d828d0eb"}
