[package]
name = "minif2f"
version = "1.0"
lean_version = "leanprover-community/lean:3.38.0"
path = "lean/src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "30a731ca565b92955e40274652f4c2b6f4db79f4"}
